{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explain-code.fullname" . }}-backend-secret
  labels:
    {{- include "explain-code.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
