{{- if .Values.ingress.enabled }}
{{- $host := include "explain-code.publicHost" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "explain-code.fullname" . }}
  labels:
    {{- include "explain-code.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- if .Values.ingress.tls.hosts }}
        {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- else }}
        - {{ $host | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "explain-code.fullname" $ }}-{{ .service }}
                port:
                  name: http
          {{- end }}
{{- end }}
